services:
    syncchat.api:
        image: ${DOCKER_REGISTRY-}syncchatapi
        build:
          context: .
          dockerfile: SyncChat.API/Dockerfile
        ports:
            - "5000:8080"
            - "5001:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
          - ./SyncChat.API:/app
        restart: unless-stopped

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: syncchatuser
            POSTGRES_PASSWORD: syncchatpass
            POSTGRES_DB: syncchatdb
        ports:
            - "5432:5432"
        # volumes:
        #     - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
